version: '3.8'

services:
  webApp1:
    image: jpetstore
    container_name: webApp1
    ports:
      - "8081:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:8006
        fluentd-buffer-limit: 1m
  
  webApp2:
      image: jpetstore
      container_name: webApp2
      ports:
        - "8082:8080"
      logging:
        driver: fluentd
        options:
          fluentd-address: localhost:8006
          fluentd-buffer-limit: 1m
  
