receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  batch: 
    send_batch_size: 500
    timeout: 10s

  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s

  filter/logs/server:
    error_mode: ignore
    logs:
      log_record:
        - 'not (IsMatch(body, "Server Log.*"))'

  filter/logs/web:
    error_mode: ignore
    logs:
      log_record:
        - 'not (IsMatch(body, "Web Log.*"))'

  filter/logs/access:
    logs:
      include:
        match_type: regexp
        bodies:
          - '^(\S+) \S+ \S+ \[(.*?)\] "(.*?)" (\d{3}) (\d+)'

exporters:
  file/server:
    path: './output/server_logs.json'
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true

  file/web:
    path: './output/web_logs.json'
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true

  file/access:
    path: './output/access_logs.json'
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true

  debug:
    verbosity: detailed

service:
  pipelines:
    logs/server:
      receivers: [fluentforward]
      processors: [batch, memory_limiter, filter/logs/server]
      exporters: [file/server]

    logs/web:
      receivers: [fluentforward]
      processors: [batch, memory_limiter, filter/logs/web]
      exporters: [file/web]

    logs/access:
      receivers: [fluentforward]
      processors: [batch, memory_limiter, filter/logs/access]
      exporters: [file/access]

